<?php

/**
 * @file
 * Contains admin_unete.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function admin_unete_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the admin_unete module.
    case 'help.page.admin_unete':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function admin_unete_theme() {
  return [
    'admin_unete' => [
      'render element' => 'children',
    ],

    'page_unete' => [
        'template' => 'page-unete',
        'path' => drupal_get_path('module', 'admin_unete').'/templates',
        'variables' => array(
            'data' => array(),
        ),
    ],
  ];
}
