<?php

/**
 * @file
 * Contains admin_news.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function admin_news_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the admin_news module.
    case 'help.page.admin_news':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function admin_news_theme() {
  return [
    'admin_news' => [
      'render element' => 'children',
    ],

    'list_news' => [
        'template' => 'list-news',
        'path' => drupal_get_path('module', 'admin_news').'/templates',
        'variables' => array(
            'info' => array(),
        ),
    ],

  ];
}
